In [1]:
import numpy as np

In [2]:
array = np.array(range(6))

In [3]:
array

array([0, 1, 2, 3, 4, 5])

In [6]:
array_2d = np.array([range(6),range(6)])

In [9]:
array_2d 

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [8]:
array.shape

(6,)

In [10]:
array_2d.size

12

In [11]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [12]:
array_2d.T.shape

(6, 2)

In [13]:
array_2d.ndim

2

In [14]:
array.ndim

1

In [15]:
array_2d.dtype

dtype('int32')

In [16]:
array.dtype

dtype('int32')

In [19]:
my_list = [x*10 for x in range(1,11)]

In [20]:
my_array = np.array(my_list)

In [21]:
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [22]:
print(f"ndim: {my_array.ndim}")
print(f"shape: {my_array.shape}")
print(f"size: {my_array.size}")
print(f"dtype: {my_array.dtype}")

ndim: 1
shape: (10,)
size: 10
dtype: int32
